sudo: required
services:
  - docker

before_install:
  - docker build -t jamesfrj/docker-react-complex-example -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jamesfrj/docker-react-complex-example npm test

after_success:
  - docker build -t jamesfrj/react-complex-client ./client
  - docker build -t jamesfrj/react-complex-nginx ./nginx
  - docker build -t jamesfrj/react-complex-server ./server
  - docker build -t jamesfrj/react-complex-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push jamesfrj/react-complex-client
  - docker push jamesfrj/react-complex-nginx
  - docker push jamesfrj/react-complex-server
  - docker push jamesfrj/react-complex-worker